// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtjsrSHfbM0KNZF5EmwFs81D3VKpWOLiY',
    appId: '1:729963763830:web:a7ac9263a48b73563be757',
    messagingSenderId: '729963763830',
    projectId: 'turotask',
    authDomain: 'turotask.firebaseapp.com',
    storageBucket: 'turotask.firebasestorage.app',
    measurementId: 'G-DV46TEB640',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiNpt-cct5m4EdG1cho93LJMCwZKKgEFY',
    appId: '1:729963763830:android:9a2c147ccef8f0fc3be757',
    messagingSenderId: '729963763830',
    projectId: 'turotask',
    storageBucket: 'turotask.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZzRIMiSQmloXUX1VpugXXkRUOYkdY2Mk',
    appId: '1:729963763830:ios:f00fa345e6bf318a3be757',
    messagingSenderId: '729963763830',
    projectId: 'turotask',
    storageBucket: 'turotask.firebasestorage.app',
    iosBundleId: 'com.example.projectApp',
  );

}